###################################


@baseUrl = http://localhost:5106
@topicId = 5
@deleteQuestionId = 28
@deleteTopicId = 4
@questionId = 29

### Submit exam
POST {{baseUrl}}/api/exam/submit/token1
Content-Type: application/json
Accept: application/json

{
    "answers": [
        { "questionId": 1, "choiceId": 2 },
        { "questionId": 2, "choiceId": 5 },
        { "questionId": 3, "choiceId": 9 },
        { "questionId": 4, "choiceId": 13 },
        { "questionId": 5, "choiceId": 17 },
        { "questionId": 6, "choiceId": 21 },
        { "questionId": 7, "choiceId": 25 },
        { "questionId": 8, "choiceId": 29 },  
        { "questionId": 9, "choiceId": 34},     
        { "questionId": 10, "choiceId": 37 }
    ]
}
